# - role: "Conference Reviewer"
#   subtitle: "Selected Venues"
#   icon: "fas fa-users"
#   description: "CVPR, ICCV, ECCV, NeurIPS, ICLR, AAAI"

# - role: "Journal Reviewer"
#   subtitle: "Peer Review"
#   icon: "fas fa-book-open"
#   description: "List journals or editorial services here."
